### PR TITLE
CSS Challenge

### PR DESCRIPTION
**Pull request by kirby-b**
I like how it looks, even if the design is kinda simple.

### CODE REVIEW

**Comment by Lightshayan** [comment]
Hey! Can you host your website to GH pages so we can see it?

**Comment by kirby-b** [comment]
Of course, I have created a repo to deploy it. It should now be up at [kirby-b.github.io/illuminate-css/](https://kirby-b.github.io/illuminate-css/)

**Comment by Lightshayan** [comment]
Hey! I love this! I will approve this and merge it. Great Job! I'll add your website to the poll.

**Review by Lightshayan — APPROVED** [review]
file check - looks good. Merge should happen now.

**Pull request merged**
