### PR TITLE
Website Challenge Submission #2

### PR DESCRIPTION
**Pull request by jeebuscrossaint**
# CSS Challenge Submission - Jeebuscrossaint

______

Here's my rendition of the site going with the darkblue-ish color-scheme with a matrix fade in effect. I added some perhaps insider information pertaining to the competition.

____

## Major Changes & Additions

- Yoinked Zach's SVG I think he is fine with it (he gave it to me)
- Spiced the navigation bar
- A countdown timer to the event and eye catching registration links
- Footer with 
- Favicon
- Floating effects

_____

## Tools Used

Everything is vanilla html css and js so I used VsCode insiders as my ide.

____

## Preview here: https://jeebuscrossaint.github.io/illuminate-site-revamp/

____

Zach Thanks for the SVGs Im sitting right next to you irl

## Screenshots

image
image
image
image

### CODE REVIEW

**Comment by Lightshayan** [comment]
Hey! Looks great, but could you make the schedule hidden and instead, have a coming soon section? That is something for us.

**Comment by jeebuscrossaint** [comment]
Alright I'll do that like tomorrow morning.

**Comment by jeebuscrossaint** [comment]
Alright I changed what you asked for! @Lightshayan

**Comment by ZachLTech** [comment]
Nice job buddy!

**Comment by jeebuscrossaint** [comment]
Zach I'm gonna go off on you when you back next week

**Comment by Lightshayan** [comment]
Great Job! I'll approve it now, and we will vote on whose will be up in a few days!

**Review by Lightshayan — APPROVED** [review]

**Pull request merged**
